### ISSUE TITLE
Project fails to build in carthage for version 1.4.3

### ISSUE THREAD

**Issue by robowen5mac** [PGSSoft/AutoMate#10]
Starting from a simple carthage.private file that contains github "PGSSoft/AutoMate", running carthage update leads to the following output:

Building scheme "AutoMate iOS" in AutoMate.xcworkspace
Build Failed
	Task failed with exit code 65:

Looking in the log file, I see the following error

extensions/XCUIElementTypeQueryProvider+Any.swift:19:49: error: 'Type' is not a member type of 'XCUIElement'
    func descendants(matching type: XCUIElement.`Type`) -> XCUIElementQuery
                                    ~~~~~~~~~~~ ^

** ARCHIVE FAILED **

The Type field above has single quote around it in the output file.

Everything works great for version 1.4.2

Is there something that needs to be set differently for 1.4.3?

**Comment by bartoszj** [comment]
Hi,
The API was changed a little bit in the Xcode 9.2. ``XCUIElement.`Type` `` was changed to ``XCUIElement.ElementType``.

I've prepared a new version, [1.4.4](XCUIElement.ElementType) which should build on Xcode 9.2 without problems.
